wrapped the "row_number" keyword
ovos/doctrine1 pull request #5
Opened 2019-11-11 18:18 UTC by marcing

2019-11-11 19:05 UTC, falkenhawk commented
thanks, but first we need to setup testing env on travis for both mysql 5.7 & 8, and fix that erroring php 5.4 and 5.5 builds: https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723

2019-11-11 19:10 UTC, falkenhawk requested changes

2019-11-11 19:10 UTC, falkenhawk commented on lib/Doctrine/Query.php
> +                    $subquery = 'SELECT @rownum:=@rownum + 1 as `row_number`,'
This should be quoted properly as follows:
```suggestion
                    $subquery = 'SELECT @rownum:=@rownum + 1 as ' . $this->_conn->quoteIdentifier('row_number') . ','
```
...then the failing test won't be failing anymore.

2019-11-11 20:46 UTC, marcing commented
> 
> 
> thanks, but first we need to setup testing env on travis for both mysql 5.7 & 8, and fix those erroring php 5.4 and 5.5 builds: https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723

PHP5 is EOL. It's a waste of time....

2019-11-12 08:58 UTC, milanorszagh commented
I don't feel certain enough in this to review it, but I will happily share my thoughts on it.

2019-11-16 22:49 UTC, falkenhawk commented
>  first we need to setup testing env on travis for both mysql 5.7 & 8

actually the test suite never really connects to the database, it only mocks connections. Few tests which used a real connection have been long commented out in the original repo. I am afraid it's not feasible to add mysql 5.7/8 specific tests with real connection in a reasonable time. However, they might be necessary in future.

Since this change has been tested for some time on a project, and no other issues with mysql 8, popped up, I could optimistically assume that this doctrine1 fork is compatible with mysql 8...

2019-11-16 22:49 UTC, falkenhawk approved these changes

2019-11-16 22:50 UTC, merged