1.3.3 release
ovos/doctrine1 pull request #8
Opened 2021-06-11 10:18 UTC by marcing

- fixed PHP8 error:
PHP Deprecated:  Required parameter $tableAliases follows optional parameter $sqlPart in lib\Doctrine\Query\Abstract.php on line 2468

2021-06-14 08:05 UTC, falkenhawk requested changes
please revert whitespace changes to avoid unnecessary clutter, thank you

2021-06-14 08:05 UTC, falkenhawk commented on CHANGELOG.md
> +- fix for Dotrine_Record::getMutators()
accidental change

2022-01-25 10:49 UTC, partikus commented
@marcing bump

2022-10-04 09:10 UTC, falkenhawk approved these changes
Well, in the end, I had to do it all by myself.

2022-10-04 09:11 UTC, merged